### Create a new user
POST https://localhost:7233/users
Content-Type: application/json

{
  "firstName": "moby",
  "lastName": "moby",
  "email": "moby@moby.moby",
  "bio": "mobymobymoby",
  "githubUrl": "mobymobymoby",
  "password": "mobymobymoby"
}

### Login
POST https://localhost:7233/login
Content-Type: application/json
{
  "password": "mobymobymoby",
  "email": "moby@moby.moby"
}